[build]
  publish = "dist"
  command = "npm run generate"
[build.environment]
  NODE_VERSION = "11"

[[redirects]]
  from = "/*"
  to = "https://www.bestonlineincometools.com"
  status = 301
  force = true